apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config
  namespace: search-service
data:
  # App
  PORT: "3000"
  NODE_ENV: "production"

  # PostgreSQL
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "search_db"

  # Elasticsearch
  ELASTICSEARCH_HOST: "elasticsearch-service"
  ELASTICSEARCH_PORT: "9200"
  ELASTIC_URL: "http://elasticsearch-service:9200"
  ELASTIC_INDEX: "products"

  # Kafka / Debezium
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_GROUP_ID: "search-service-consumer"
  KAFKA_TOPIC: "dbserver1.public.Product"

  # Search engine
  SEARCH_ENGINE: "elastic"
