apiVersion: v1
kind: Secret
metadata:
  name: search-service-secrets
  namespace: search-service
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/search_db"
  
